site_name: TinyBear Documentation
site_url: https://lemontree210.github.io/tinybear/
extra:
  base_url: /tinybear/
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Usage: usage.md
  - API Reference: api.md
docs_dir: docs
site_dir: site
theme:
  name: material
  features:
    - navigation.instant  # âš¡ Instant loading
    - navigation.tracking  # ğŸ“Š Track scroll position
    - navigation.tabs.sticky  # ğŸ“Œ Sticky navigation
    - navigation.top  # â¬†ï¸ Back to top button
    - search.suggest  # ğŸ” Search suggestions
    - search.share  # ğŸ”— Share search
    - header.autohide  # ğŸ© Auto-hide header
    - content.code.annotate  # ğŸ’¡ Code annotations